apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tomasferrarisenda/infra-tools-helm-charts.git # This value was modified by the initial-setup script
    # path: helm-charts/infra/argo-cd
    path: argo-cd
    helm:
      valueFiles:
        - values-custom.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
